# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfazMenu.ui'
#
# Created: Sun Nov 13 16:32:26 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1063, 712)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1351, 681))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(240, 10, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(370, 150, 641, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setScaledContents(False)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(270, 250, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setScaledContents(False)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(250, 320, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setScaledContents(False)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(210, 390, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setScaledContents(False)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.TabP1 = QtGui.QWidget()
        self.TabP1.setObjectName(_fromUtf8("TabP1"))
        self.label_2 = QtGui.QLabel(self.TabP1)
        self.label_2.setGeometry(QtCore.QRect(420, -10, 331, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.nombreCantidadCarreteras = QtGui.QLabel(self.TabP1)
        self.nombreCantidadCarreteras.setGeometry(QtCore.QRect(50, 90, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras.setFont(font)
        self.nombreCantidadCarreteras.setObjectName(_fromUtf8("nombreCantidadCarreteras"))
        self.scrollArea = QtGui.QScrollArea(self.TabP1)
        self.scrollArea.setGeometry(QtCore.QRect(680, 90, 321, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 279))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.nombreCantidadCarreteras_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.nombreCantidadCarreteras_4.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_4.setFont(font)
        self.nombreCantidadCarreteras_4.setAlignment(QtCore.Qt.AlignCenter)
        self.nombreCantidadCarreteras_4.setObjectName(_fromUtf8("nombreCantidadCarreteras_4"))
        self.labelTransisiones = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelTransisiones.setGeometry(QtCore.QRect(20, 50, 281, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTransisiones.sizePolicy().hasHeightForWidth())
        self.labelTransisiones.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setBold(False)
        font.setWeight(50)
        self.labelTransisiones.setFont(font)
        self.labelTransisiones.setText(_fromUtf8(""))
        self.labelTransisiones.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTransisiones.setWordWrap(True)
        self.labelTransisiones.setMargin(3)
        self.labelTransisiones.setObjectName(_fromUtf8("labelTransisiones"))
        self.labelTransisiones2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelTransisiones2.setGeometry(QtCore.QRect(20, 150, 281, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTransisiones2.sizePolicy().hasHeightForWidth())
        self.labelTransisiones2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setBold(False)
        font.setWeight(50)
        self.labelTransisiones2.setFont(font)
        self.labelTransisiones2.setText(_fromUtf8(""))
        self.labelTransisiones2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTransisiones2.setWordWrap(True)
        self.labelTransisiones2.setMargin(3)
        self.labelTransisiones2.setObjectName(_fromUtf8("labelTransisiones2"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tableWidgetBasesP1 = QtGui.QTableWidget(self.TabP1)
        self.tableWidgetBasesP1.setGeometry(QtCore.QRect(220, 140, 441, 111))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetBasesP1.sizePolicy().hasHeightForWidth())
        self.tableWidgetBasesP1.setSizePolicy(sizePolicy)
        self.tableWidgetBasesP1.setAlternatingRowColors(True)
        self.tableWidgetBasesP1.setObjectName(_fromUtf8("tableWidgetBasesP1"))
        self.tableWidgetBasesP1.setColumnCount(3)
        self.tableWidgetBasesP1.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBasesP1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBasesP1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetBasesP1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetBasesP1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetBasesP1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetBasesP1.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetBasesP1.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetBasesP1.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetBasesP1.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetBasesP1.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetBasesP1.setItem(1, 2, item)
        self.tableWidgetBasesP1.horizontalHeader().setCascadingSectionResizes(False)
        self.nombreCantidadCarreteras_2 = QtGui.QLabel(self.TabP1)
        self.nombreCantidadCarreteras_2.setGeometry(QtCore.QRect(50, 260, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_2.setFont(font)
        self.nombreCantidadCarreteras_2.setObjectName(_fromUtf8("nombreCantidadCarreteras_2"))
        self.tableWidgetVectorP1 = QtGui.QTableWidget(self.TabP1)
        self.tableWidgetVectorP1.setGeometry(QtCore.QRect(220, 290, 441, 81))
        self.tableWidgetVectorP1.setAlternatingRowColors(True)
        self.tableWidgetVectorP1.setObjectName(_fromUtf8("tableWidgetVectorP1"))
        self.tableWidgetVectorP1.setColumnCount(3)
        self.tableWidgetVectorP1.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetVectorP1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetVectorP1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetVectorP1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetVectorP1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetVectorP1.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetVectorP1.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetVectorP1.setItem(0, 2, item)
        self.scrollArea_3 = QtGui.QScrollArea(self.TabP1)
        self.scrollArea_3.setGeometry(QtCore.QRect(30, 410, 971, 191))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 969, 189))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.nombreCantidadCarreteras_6 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.nombreCantidadCarreteras_6.setGeometry(QtCore.QRect(10, 10, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_6.setFont(font)
        self.nombreCantidadCarreteras_6.setAlignment(QtCore.Qt.AlignCenter)
        self.nombreCantidadCarreteras_6.setObjectName(_fromUtf8("nombreCantidadCarreteras_6"))
        self.labelCombinaciones = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.labelCombinaciones.setGeometry(QtCore.QRect(20, 50, 911, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCombinaciones.sizePolicy().hasHeightForWidth())
        self.labelCombinaciones.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setBold(False)
        font.setWeight(50)
        self.labelCombinaciones.setFont(font)
        self.labelCombinaciones.setText(_fromUtf8(""))
        self.labelCombinaciones.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCombinaciones.setWordWrap(True)
        self.labelCombinaciones.setMargin(3)
        self.labelCombinaciones.setObjectName(_fromUtf8("labelCombinaciones"))
        self.labelCombinaciones2 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.labelCombinaciones2.setGeometry(QtCore.QRect(20, 110, 911, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCombinaciones2.sizePolicy().hasHeightForWidth())
        self.labelCombinaciones2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setBold(False)
        font.setWeight(50)
        self.labelCombinaciones2.setFont(font)
        self.labelCombinaciones2.setText(_fromUtf8(""))
        self.labelCombinaciones2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCombinaciones2.setWordWrap(True)
        self.labelCombinaciones2.setMargin(3)
        self.labelCombinaciones2.setObjectName(_fromUtf8("labelCombinaciones2"))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.pushButtonCalcularTrans = QtGui.QPushButton(self.TabP1)
        self.pushButtonCalcularTrans.setGeometry(QtCore.QRect(360, 380, 181, 23))
        self.pushButtonCalcularTrans.setObjectName(_fromUtf8("pushButtonCalcularTrans"))
        self.tabWidget.addTab(self.TabP1, _fromUtf8(""))
        self.TapP2 = QtGui.QWidget()
        self.TapP2.setObjectName(_fromUtf8("TapP2"))
        self.label_3 = QtGui.QLabel(self.TapP2)
        self.label_3.setGeometry(QtCore.QRect(420, -10, 351, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tableWidgetBaseR2P2 = QtGui.QTableWidget(self.TapP2)
        self.tableWidgetBaseR2P2.setGeometry(QtCore.QRect(210, 170, 341, 91))
        self.tableWidgetBaseR2P2.setAlternatingRowColors(True)
        self.tableWidgetBaseR2P2.setObjectName(_fromUtf8("tableWidgetBaseR2P2"))
        self.tableWidgetBaseR2P2.setColumnCount(2)
        self.tableWidgetBaseR2P2.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBaseR2P2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetBaseR2P2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetBaseR2P2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetBaseR2P2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidgetBaseR2P2.setItem(0, 1, item)
        self.nombreCantidadCarreteras_3 = QtGui.QLabel(self.TapP2)
        self.nombreCantidadCarreteras_3.setGeometry(QtCore.QRect(60, 100, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_3.setFont(font)
        self.nombreCantidadCarreteras_3.setObjectName(_fromUtf8("nombreCantidadCarreteras_3"))
        self.tableWidgetBaseR3P2 = QtGui.QTableWidget(self.TapP2)
        self.tableWidgetBaseR3P2.setGeometry(QtCore.QRect(160, 390, 481, 81))
        self.tableWidgetBaseR3P2.setAlternatingRowColors(True)
        self.tableWidgetBaseR3P2.setObjectName(_fromUtf8("tableWidgetBaseR3P2"))
        self.tableWidgetBaseR3P2.setColumnCount(3)
        self.tableWidgetBaseR3P2.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBaseR3P2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetBaseR3P2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetBaseR3P2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        self.tableWidgetBaseR3P2.setHorizontalHeaderItem(2, item)
        self.nombreCantidadCarreteras_5 = QtGui.QLabel(self.TapP2)
        self.nombreCantidadCarreteras_5.setGeometry(QtCore.QRect(60, 340, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_5.setFont(font)
        self.nombreCantidadCarreteras_5.setObjectName(_fromUtf8("nombreCantidadCarreteras_5"))
        self.scrollArea_2 = QtGui.QScrollArea(self.TapP2)
        self.scrollArea_2.setGeometry(QtCore.QRect(680, 60, 321, 281))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 319, 279))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.nombreCantidadCarreteras_7 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.nombreCantidadCarreteras_7.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_7.setFont(font)
        self.nombreCantidadCarreteras_7.setAlignment(QtCore.Qt.AlignCenter)
        self.nombreCantidadCarreteras_7.setObjectName(_fromUtf8("nombreCantidadCarreteras_7"))
        self.labelR2Ortonormal = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.labelR2Ortonormal.setGeometry(QtCore.QRect(20, 50, 281, 211))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelR2Ortonormal.sizePolicy().hasHeightForWidth())
        self.labelR2Ortonormal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setBold(False)
        font.setWeight(50)
        self.labelR2Ortonormal.setFont(font)
        self.labelR2Ortonormal.setText(_fromUtf8(""))
        self.labelR2Ortonormal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelR2Ortonormal.setWordWrap(True)
        self.labelR2Ortonormal.setMargin(3)
        self.labelR2Ortonormal.setObjectName(_fromUtf8("labelR2Ortonormal"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_4 = QtGui.QScrollArea(self.TapP2)
        self.scrollArea_4.setGeometry(QtCore.QRect(680, 350, 321, 281))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 319, 279))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.nombreCantidadCarreteras_8 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.nombreCantidadCarreteras_8.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombreCantidadCarreteras_8.setFont(font)
        self.nombreCantidadCarreteras_8.setAlignment(QtCore.Qt.AlignCenter)
        self.nombreCantidadCarreteras_8.setObjectName(_fromUtf8("nombreCantidadCarreteras_8"))
        self.labelR3Ortonormal = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.labelR3Ortonormal.setGeometry(QtCore.QRect(20, 50, 281, 211))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelR3Ortonormal.setFont(font)
        self.labelR3Ortonormal.setText(_fromUtf8(""))
        self.labelR3Ortonormal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelR3Ortonormal.setWordWrap(True)
        self.labelR3Ortonormal.setMargin(3)
        self.labelR3Ortonormal.setObjectName(_fromUtf8("labelR3Ortonormal"))
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.pushButtonCalcularR2P2 = QtGui.QPushButton(self.TapP2)
        self.pushButtonCalcularR2P2.setGeometry(QtCore.QRect(310, 280, 75, 23))
        self.pushButtonCalcularR2P2.setObjectName(_fromUtf8("pushButtonCalcularR2P2"))
        self.pushButtonCalcularR3P2 = QtGui.QPushButton(self.TapP2)
        self.pushButtonCalcularR3P2.setGeometry(QtCore.QRect(310, 500, 75, 23))
        self.pushButtonCalcularR3P2.setObjectName(_fromUtf8("pushButtonCalcularR3P2"))
        self.tabWidget.addTab(self.TapP2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", "Proyecto 2 Álgebra Lineal", None))
        self.label_17.setText(_translate("MainWindow", "Integrantes", None))
        self.label_19.setText(_translate("MainWindow", "Liza Chaves Carranza", None))
        self.label_20.setText(_translate("MainWindow", "Bryan Jiménez Chacón", None))
        self.label_21.setText(_translate("MainWindow", "Luis Alonso Pacheco Nuñez", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "About", None))
        self.label_2.setText(_translate("MainWindow", "Programa 1", None))
        self.nombreCantidadCarreteras.setText(_translate("MainWindow", "1. Digite los vectores de las bases B y  B\'  Ej: (1,1,1) (1,1,0) (1,0,0)", None))
        self.nombreCantidadCarreteras_4.setText(_translate("MainWindow", "Matrices de Transición B y B\'", None))
        item = self.tableWidgetBasesP1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "B", None))
        item = self.tableWidgetBasesP1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B\'", None))
        item = self.tableWidgetBasesP1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vector a", None))
        item = self.tableWidgetBasesP1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector b", None))
        item = self.tableWidgetBasesP1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vector c", None))
        __sortingEnabled = self.tableWidgetBasesP1.isSortingEnabled()
        self.tableWidgetBasesP1.setSortingEnabled(False)
        self.tableWidgetBasesP1.setSortingEnabled(__sortingEnabled)
        self.nombreCantidadCarreteras_2.setText(_translate("MainWindow", "2. Digite un vector u de R3 Ej: (1,3,-2)", None))
        item = self.tableWidgetVectorP1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "u", None))
        item = self.tableWidgetVectorP1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Elemento a", None))
        item = self.tableWidgetVectorP1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Elemento b", None))
        item = self.tableWidgetVectorP1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Elemento c", None))
        __sortingEnabled = self.tableWidgetVectorP1.isSortingEnabled()
        self.tableWidgetVectorP1.setSortingEnabled(False)
        self.tableWidgetVectorP1.setSortingEnabled(__sortingEnabled)
        self.nombreCantidadCarreteras_6.setText(_translate("MainWindow", "Vector u como Combinacion Lineal de B y B\'", None))
        self.pushButtonCalcularTrans.setText(_translate("MainWindow", "Calcular", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabP1), _translate("MainWindow", "Programa 1", None))
        self.label_3.setText(_translate("MainWindow", "Programa 2", None))
        item = self.tableWidgetBaseR2P2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Base de R2", None))
        item = self.tableWidgetBaseR2P2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vector a", None))
        item = self.tableWidgetBaseR2P2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector b", None))
        __sortingEnabled = self.tableWidgetBaseR2P2.isSortingEnabled()
        self.tableWidgetBaseR2P2.setSortingEnabled(False)
        self.tableWidgetBaseR2P2.setSortingEnabled(__sortingEnabled)
        self.nombreCantidadCarreteras_3.setText(_translate("MainWindow", "1.Ingrese la base de R2   Ej:  (2, 3, 1)  (1, 2, 4)", None))
        item = self.tableWidgetBaseR3P2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Base de R3", None))
        item = self.tableWidgetBaseR3P2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vector a", None))
        item = self.tableWidgetBaseR3P2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector b", None))
        item = self.tableWidgetBaseR3P2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vector c", None))
        self.nombreCantidadCarreteras_5.setText(_translate("MainWindow", "2.Ingrese la base de R3  Ej:  (1, 1, 1) (2, 3,1)  (1, 2, 4)", None))
        self.nombreCantidadCarreteras_7.setText(_translate("MainWindow", "Base Ortonormal de R2", None))
        self.nombreCantidadCarreteras_8.setText(_translate("MainWindow", "Base Ortonormal de R3", None))
        self.pushButtonCalcularR2P2.setText(_translate("MainWindow", "Calcular", None))
        self.pushButtonCalcularR3P2.setText(_translate("MainWindow", "Calcular", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TapP2), _translate("MainWindow", "Programa 2", None))

